In [5]:
import numpy as np
lst=[1,2,3,4,5]
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(lst)
print(type(lst))
print(arr*2)
print(lst*2)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
<class 'list'>
[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape) #shape ie in this case 3,3
print(arr.ndim) #dimension of a matrix
print(arr.size) # total elements
print(arr.dtype)
np.zeros((2,2))
np.ones((3,3))
np.full((3,3),7)
identitiy_matrix=np.eye(3) #identitiy matrix 
print(identitiy_matrix)
np.arange(1,20,2)
np.linspace(0,10,3) # give me 3 no between 0 and 10

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9
int64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

array([ 0.,  5., 10.])

In [3]:
a=np.array([5,10,15,20,25])
print(a)
b=np.arange(5,26,5)
print(b)
c=np.full((3,3),1)
print(c)
d=np.array([[10,20],[30,40],[50,60]])
print(d.ndim)
print(d.shape)
print(d.size)
np.linspace(0,100,6)

[ 5 10 15 20 25]
[ 5 10 15 20 25]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
2
(3, 2)
6

array([  0.,  20.,  40.,  60.,  80., 100.])

In [5]:
print(np.full((3,3),7))
np.arange(1,10,2)

[[7 7 7]
 [7 7 7]
 [7 7 7]]

array([1, 3, 5, 7, 9])

In [15]:
number=([1,2,3,4,5])
print(number[0])
print(number[1])
print(number[2])
print(number[3])
print(number[4],end='\n\n')

it=iter(number)
for i in range(len(number)):
    print(next(it))
print(type(it))
print(type(number))

1
2
3
4
5

1
2
3
4
5
<class 'list_iterator'>
<class 'list'>

In [17]:
number1=([1,2,3,4,5])
it1=iter(number1)
it2=iter(number1)
#both it1 and it2 are different object 
for i in range(len(number)):
    print(next(it1))
for i in range(len(number)):
    print(next(it2))

1
2
3
4
5
1
2
3
4
5

In [18]:
#for x in [10,20,30,40,50]:
#    print(x)

number=[10,20,30,40,50]
it =iter(number)
while True:
    try:
        value=next(it)
        print(value)
    except StopIteration:
        break

10
20
30
40
50

In [25]:
class Student:
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def __str__(self): #for normal audience
        return self.name
    def __repr__(self): #for developers 
        return 'Student(BMW)'
aryan=Student('Aryan')
print(aryan) #<__main__.Student object at 0x0000015E9B5E1850>
print(aryan.getName())
print(aryan)

Student(BMW)
Aryan
Student(BMW)

In [37]:
a=np.array([10,20,30,40,50])

print('Max : ',a.max())
print('Min : ',a.min())
print('Mean : ',a.mean())
print('Sum : ',a.sum())
print('standard deviation : ',a.std())
print('Variance : ',a.var())
print('Percentile ',np.percentile(a,30))
print('coeff of variation : ',(a.std()/a.mean()))
print('Range : ',a.max()-a.min())

Max :  50
Min :  10
Mean :  30.0
Sum :  150
standard deviation :  14.142135623730951
Variance :  200.0
Percentile  22.0
coeff of variation :  0.4714045207910317
Range :  40

In [31]:
arr=np.array([
    [1,2,3],
    [4,5,6]
])
print(arr)
print(arr.sum(axis=0)) #column sum
print(arr.sum(axis=1)) #row sum

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]

In [32]:
a = np.array([12,45,8,99,34])

print(a.max())
print(a.argmax()) #index at which the max value is at 
print(a.min())
print(a.argmin()) #index at which the min value is at

99
3
8
2

In [46]:
arr=np.arange(1,26,1).reshape(5,5)
print(arr)
print('third row  :',arr[2])
print('second column : ',arr[:,1])
new_arr=arr[1:4,1:4].copy()
print(new_arr)
print("sum of each row : ",arr.sum(axis=1))
print(arr+100)
new_arr[1,1]=999
print(new_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
third row  : [11 12 13 14 15]
second column :  [ 2  7 12 17 22]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
sum of each row :  [ 15  40  65  90 115]
[[101 102 103 104 105]
 [106 107 108 109 110]
 [111 112 113 114 115]
 [116 117 118 119 120]
 [121 122 123 124 125]]
[[  7   8   9]
 [ 12 999  14]
 [ 17  18  19]]

In [60]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.full((3,3),7))
print(np.eye(3,3))
print(np.arange(1,10,2))
print(np.linspace(0,10,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[ 0.  5. 10.]

In [75]:
arr=np.array([10,20,30,40,50,52])
print(arr>25)
print(arr[arr>25])
print(arr[arr%2==0])
arr1=np.array([10,2,5,57,3])
arr2=np.array([
    [1,2,3],
    [4,5,6]
])
print(np.sort(arr1))
print(np.argsort(arr1))
print(arr2.flatten())

[False False  True  True  True  True]
[30 40 50 52]
[10 20 30 40 50 52]
[ 2  3  5 10 57]
[1 4 2 0 3]
[1 2 3 4 5 6]
None

In [100]:
import pandas as pd 
s=pd.Series([10,20,30,40,50],
            index=['Math','English','Physics','Chemistry','Hindi'])
print(s)
value=s.values
print(value)
print(s.index)
print("data type : ",s.dtype)
print('shape : ',s.shape)
print(s['Math'])
print(s.iloc[1])
print(s.loc['Hindi'])
print(s+5)
print(s>25)
print(s[s>25])

Math         10
English      20
Physics      30
Chemistry    40
Hindi        50
dtype: int64
[10 20 30 40 50]
Index(['Math', 'English', 'Physics', 'Chemistry', 'Hindi'], dtype='str')
data type :  int64
shape :  (5,)
10
20
50
Math         15
English      25
Physics      35
Chemistry    45
Hindi        55
dtype: int64
Math         False
English      False
Physics       True
Chemistry     True
Hindi         True
dtype: bool
Physics      30
Chemistry    40
Hindi        50
dtype: int64

In [103]:
#dictonary 
data={
    'Math':90,
    'English':80,
    'Hindi':100
}
s=pd.Series(data)
print(s)

Math        90
English     80
Hindi      100
dtype: int64

In [108]:
import numpy as np
s=pd.Series([10,20,np.nan,40])
print(s.isnull())
print('No of null value : ',s.isnull().sum())

0    False
1    False
2     True
3    False
dtype: bool
No of null value :  1
20.0

In [109]:
s=pd.Series([10,20,30,40,50])
print(s.sum())
print(s.max())
print(s.min())
print(s.mean())
print(s.std())
print(s.var())
print(s.unique())
print(s.nunique())

150
50
10
30.0
15.811388300841896
250.0
[10 20 30 40 50]
5

In [114]:
s = pd.Series([1,2,2,3,3,3,4])
print(s.value_counts())
#print(s.sort_values(ascending=False)) #decending value 
#print(s.sort_values(ascending=True)) #ascending value
print(s.describe())

3    3
2    2
1    1
4    1
Name: count, dtype: int64
count    7.000000
mean     2.571429
std      0.975900
min      1.000000
25%      2.000000
50%      3.000000
75%      3.000000
max      4.000000
dtype: float64
2.5714285714285716

In [135]:
data ={
    'Name':['A','B','C','D'],
    'Age':[20,25,30,35],
    'Salary':[1000,1500,2000,2500],
    
}
df=pd.DataFrame(data)
print(df)
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.info)

  Name  Age  Salary
0    A   20    1000
1    B   25    1500
2    C   30    2000
3    D   35    2500
(4, 3)
Index(['Name', 'Age', 'Salary'], dtype='str')
Name        str
Age       int64
Salary    int64
dtype: object
<bound method DataFrame.info of   Name  Age  Salary
0    A   20    1000
1    B   25    1500
2    C   30    2000
3    D   35    2500>

In [133]:
data = {
    'Name':['A','B','C','D'],
    'Age':[20,25,30,35],
    'Salary':[10000,20000,30000,40000]
}
df=pd.DataFrame(data)
print(df)
print(df['Age']>25)
age_25=df[df['Age']>25]
df[(df['Age']>25) & (df['Salary']>30000)]

  Name  Age  Salary
0    A   20   10000
1    B   25   20000
2    C   30   30000
3    D   35   40000
0    False
1    False
2     True
3     True
Name: Age, dtype: bool

  Name  Age  Salary
3    D   35   40000

In [145]:
df = pd.DataFrame({
    'Name':['A','B','C']
}, index=[10,20,30])
df.iloc[1] #index  
df.loc[20] #label

Name    B
Name: 20, dtype: str

In [162]:
df = pd.DataFrame({
    'Name':['A','B','C','D'],
    'Department':['IT','HR','IT','HR'],
    'Salary':[50000,40000,60000,30000]
})
df=df.sort_values(['Department','Salary'])
df
s=pd.Series([
    'IT',
    'HR',
    'IT',
    'Finance',
    'HR'])
unique=s.unique()
no_unique=s.nunique()
print(unique)
print(no_unique)
s.value_counts()

<ArrowStringArray>
['IT', 'HR', 'Finance']
Length: 3, dtype: str
3

IT         2
HR         2
Finance    1
Name: count, dtype: int64

In [172]:
import numpy as np 
import pandas as pd 

s=pd.Series([10,20,30,np.nan,50])
s.isnull()
no_nulls=s.isnull().sum()
print(no_nulls)

df = pd.DataFrame({
    'Name':['A','B','C','D'],
    'Age':[20,np.nan,30,np.nan],
    'Salary':[10000,20000,np.nan,40000]
})
df.isnull()
df.isnull().sum()
df.fillna(0) #fills null value swith 0
df.dropna() #removes null values

1

  Name   Age   Salary
0    A  20.0  10000.0
1    B   0.0  20000.0
2    C  30.0      0.0
3    D   0.0  40000.0

In [177]:
df = pd.DataFrame({
    'Department':['IT','HR','IT','Finance','HR'],
    'Salary':[50000,30000,70000,60000,40000]
})
df.groupby('Department')['Salary'].max()
df.groupby('Department')['Salary'].agg(['mean','max','min','count'])

               mean    max    min  count
Department
Finance     60000.0  60000  60000      1
HR          35000.0  40000  30000      2
IT          60000.0  70000  50000      2

In [ ]:
#to read a csv file : 
#df=pd.read_csv("name_of_the_file.csv")

In [4]:
import pandas as pd
df1=pd.DataFrame({
    'EmployeeId': [1, 2, 3],
    'Name': ['Aryan','Rahul','Priya']
})
df2=pd.DataFrame({
    'EmployeeId': [1, 2, 3],
    'Salary': [60000,50000,70000]
})
pd.merge(df1,df2,on='EmployeeId')

   EmployeeId   Name  Salary
0           1  Aryan   60000
1           2  Rahul   50000
2           3  Priya   70000

In [5]:
df=pd.DataFrame({
    'User':['A','B','C','D'],
    'Country':['India','India','USA','USA'],
    'WatchTime':[120,80,150,90]
})
df.groupby('Country')['WatchTime'].mean()

Country
India    100.0
USA      120.0
Name: WatchTime, dtype: float64

In [9]:
df=pd.DataFrame({
    'User':['A','B','C','D'],
    'Country':['India','India','USA','USA'],
    'WatchTime':[120,80,150,90]
})
df.pivot_table(
    values='WatchTime',
    index='Country',
    aggfunc='mean'
)

         WatchTime
Country
India        100.0
USA          120.0

In [10]:
df=pd.DataFrame({
    'City':['Pune','Pune','Mumbai','Mumbai'],
    'Gender':['M','F','M','F'],
    'Sales':[100,200,150,250]
})
df.pivot_table(
    values='Sales',
    index='City',
    columns='Gender',
    aggfunc='mean'
)

Gender      F      M
City
Mumbai  250.0  150.0
Pune    200.0  100.0

In [ ]:
df=pd.read_excel('pandas.xlsx',
                 #usecols=['Name','Salary']     to read the rows needed
                 #nrows=2                       to read specific rows
                 #skiprows=2                    to skip rows in a document
                 #index_col='abc'               to set the name of the index column
                 )
#df=df.rename(columns={'EmployeeID':'EmpId'})    to change the column name
#before starting anyhting do this
df.head()
df.describe()
df.info()
df.isnull().sum()
df

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  3 non-null      int64
 1   Name        3 non-null      str
 2   Department  3 non-null      str
 3   Salary      3 non-null      int64
dtypes: int64(2), str(2)
memory usage: 254.0 bytes

   EmployeeID   Name Department  Salary
0         101  Aryan         IT   60000
1         102  Rahul         HR   50000
2         103  Priya    Finance   70000

In [ ]:
df1=pd.DataFrame({
    'Name':['A','B'],
    'Salary':[1000,2000]
})
df2=pd.DataFrame({
    'Name':['C','D'],
    'Salary':[3000,4000]
})
pd.concat([df1,df2],ignore_index=True)#index_ingore is used to duplicating index when concatinating

  Name  Salary
0    A    1000
1    B    2000
2    C    3000
3    D    4000

In [34]:
df1=pd.DataFrame({
    'Name':['A','B']
})
df2=pd.DataFrame({
    'Salary':[1000,2000]
})
pd.concat([df1,df2],axis=1)

  Name  Salary
0    A    1000
1    B    2000

In [35]:
df1=pd.DataFrame({
    'Name':['A','B'],
    'Salary':[100,200]
})
df2=pd.DataFrame({
    'Name':['C','D'],
    'Salary':[300,400]
})
pd.concat([df1,df2],ignore_index=True)

  Name  Salary
0    A     100
1    B     200
2    C     300
3    D     400

In [38]:
def grade(marks):
    if marks>=50:
        return 'Pass'
    elif marks<50:
        return 'Fail'
df=pd.DataFrame({
    'Marks':[40,60,85]
})
df['Marks'].apply(grade)

0    Fail
1    Pass
2    Pass
Name: Marks, dtype: str

In [ ]:
def grade(marks):
    if marks>=150:
        return 'Pass'
    elif marks<150:
        return 'Fail'
def total_marks(row):
    return row['Maths']+row['Science']
df=pd.DataFrame({
    'Maths':[80,70,90],
    'Science':[90,60,95]
})
df['Total']=df.apply(total_marks,axis=1) #axis 1 means that we are going row wise 
df['Total'].apply(grade)

0    Pass
1    Fail
2    Pass
Name: Total, dtype: str

In [55]:
import pandas as pd 
def result(row):
    if row['Maths']+row['Science']>=130:
        return 'Pass'
    else:
        return 'Fail'
df=pd.DataFrame({
    'Maths':[50,70,90],
    'Science':[40,80,60]
})
df['Result']=df.apply(result,axis=1)
df

   Maths  Science Result
0     50       40   Fail
1     70       80   Pass
2     90       60   Pass

In [ ]:
df=pd.dataFrame({
    'Gender'=
})